language: php

dist: trusty
sudo: false

cache:
  directories:
    - vendor

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--prefer-lowest --prefer-stable"

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer update --no-interaction --prefer-dist $DEPENDENCIES

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse -l 6 -c phpstan.neon src tests

branches:
  only:
    - master
